import { Shield } from "lucide-react";
import { Card } from "@/components/ui/card";

export function EthicalNotice() {
  return (
    <Card className="p-5 border-primary/20" style={{ background: "var(--gradient-subtle)" }}>
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10">
          <Shield className="h-4 w-4 text-primary" />
        </div>
        <div>
          <h3 className="text-sm font-semibold">Responsible AI</h3>
          <p className="mt-1 text-xs text-muted-foreground leading-relaxed">
            Outputs are generated by AI and may contain inaccuracies or bias. Always review before
            professional use, never share confidential data, and verify factual claims with trusted
            sources.
          </p>
        </div>
      </div>
    </Card>
  );
}
